[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    X-Frame-Options = "DENY;"
    X-Content-Type-Options = "nosniff;"
    X-XSS-Protection = "1; mode=block;"

